[tox]
envlist = py3, pypy3
skip_missing_interpreters = true

[testenv]
extras = test

commands =
  {envpython} -m pytest {posargs:}
  {envpython} -m pylint cpplint.py
  {envpython} -m flake8 cpplint.py
